development:
  adapter: postgresql
  encoding: unicode
  database: codernuze_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: codernuze_production
  pool: 5
  username: postgres
  password:

